version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk  # Install OpenJDK 17
      - run:
          name: Install Android SDK
          command: |
            wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip
            mkdir -p Android/Sdk
            unzip commandlinetools-linux-6200805_latest.zip -d Android/Sdk
            echo 'export ANDROID_HOME=$HOME/Android/Sdk' >> $BASH_ENV
            echo 'export PATH="$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH"'
            source $BASH_ENV
            echo $ANDROID_HOME
            sdkmanager --sdk_root=${ANDROID_HOME} "tools"
            sdkmanager --update
            sdkmanager --list
            sdkmanager "build-tools;28.0.3" "platform-tools" "platforms;android-28" "tools"
            sdkmanager --licenses
      - run:
          name: Set JAVA_HOME
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Create local.properties
          command: |
            echo "sdk.dir=/usr/lib/android-sdk" > android/local.properties
      - run:
          name: Accept licences
          command: sdkmanager.bat --licenses
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Android App
          command: |
            cd android
            ./gradlew assembleRelease  # Adjust if necessary
      - run:
          name: Build the iOS App
          command: |
            cd ios
            xcodebuild -workspace TestAppCICD.xcworkspace -scheme TestAppCICD -sdk iphoneos -configuration Release archive -archivePath $PWD/build/TestAppCICD.xcarchive

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
