version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk  # Adjust the version if necessary
      - run:
          name: Set JAVA_HOME
          command: |
            echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Android App
          command: |
            cd android
            ./gradlew assembleRelease  # Adjust if necessary
      - run:
          name: Build the iOS App
          command: |
            cd ios
            xcodebuild -workspace TestAppCICD.xcworkspace -scheme TestAppCICD -sdk iphoneos -configuration Release archive -archivePath $PWD/build/TestAppCICD.xcarchive

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
